In [ ]:
# import pandas as pd 
# data =[1,2,3,4,5]
# series = pd.Series(data)
# print("series\n,"series)

In [1]:
import sys
print(sys.executable)

c:\Users\nidhi\OneDrive\Desktop\desktop-folder\Code\venv\python.exe

In [1]:

import sys
print(sys.executable)

c:\Users\nidhi\OneDrive\Desktop\desktop-folder\Code\venv\Scripts\python.exe

In [2]:
import pandas as pd

In [4]:
## series 
import pandas as pd
data =[1,2,3,4]
series=pd.Series(data) 
print("series\n",series)

series
 0    1
1    2
2    3
3    4
dtype: int64

In [5]:
data = {'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data =[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [9]:
##DAta frame
#create a dtaframe form dictonary of list

data={
    'Name':['nidhi','bhaiya','radhe','krishna'],
    'age':[20,22,111000,1110000],
    'City':['lucknow','newyork','man ke marji','man ke marji ke piche']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

      Name      age                   City
0    nidhi       20                lucknow
1   bhaiya       22                newyork
2    radhe   111000           man ke marji
3  krishna  1110000  man ke marji ke piche
<class 'pandas.DataFrame'>

In [50]:
data=[
    {'name': 'nidhi','age':20,'city':'lucknow'},
    {'name': 'bhaiya','age':22,'city':'newyork'},
    {'name': 'radha krishna','age':20000000,'city':'heart'},
    {'name': 'krishna','age':111111110,'city':'inside that heart'}
]
df=pd.DataFrame(data)
print(df)
print(type(df))

            name        age               city
0          nidhi         20            lucknow
1         bhaiya         22            newyork
2  radha krishna   20000000              heart
3        krishna  111111110  inside that heart
<class 'pandas.DataFrame'>

In [16]:
# df= pd.read_csv('sales_data.csv')
# df.head(5)

data

[{'name': 'nidhi', 'age': 20, 'city': 'lucknow'},
 {'name': 'bhaiya', 'age': 22, 'city': 'newyork'},
 {'name': 'radha', 'age': 20000000, 'city': 'heart'},
 {'name': 'krishna', 'age': 111111110, 'city': 'inside that heart'}]

In [18]:
df['name']

0      nidhi
1     bhaiya
2      radha
3    krishna
Name: name, dtype: str

In [33]:
df.loc[0]

name      nidhi
age          20
city    lucknow
Name: 0, dtype: object

In [35]:
df.iloc[1]

name     bhaiya
age          22
city    newyork
Name: 1, dtype: object

In [38]:
df

      name        age               city
0    nidhi         20            lucknow
1   bhaiya         22            newyork
2    radha   20000000              heart
3  krishna  111111110  inside that heart

In [37]:
## accesing a specified element
df.at[1,'age']

np.int64(22)

In [39]:
df.at[2,'name']

'radha'

In [40]:
df.iat[2,2]

'heart'

In [41]:
## data manupulation with dataframe

df

      name        age               city
0    nidhi         20            lucknow
1   bhaiya         22            newyork
2    radha   20000000              heart
3  krishna  111111110  inside that heart

In [42]:
df['Salary']=[500000000,50000000000000000000,100000000,123456789]
df

      name        age               city                Salary
0    nidhi         20            lucknow             500000000
1   bhaiya         22            newyork  50000000000000000000
2    radha   20000000              heart             100000000
3  krishna  111111110  inside that heart             123456789

In [43]:
df.drop('age',axis=1,inplace=True)

In [44]:
df

      name               city                Salary
0    nidhi            lucknow             500000000
1   bhaiya            newyork  50000000000000000000
2    radha              heart             100000000
3  krishna  inside that heart             123456789

In [46]:
df['Salary']=df['Salary']+1000000

In [47]:
df

      name               city                Salary
0    nidhi            lucknow             501000000
1   bhaiya            newyork  50000000000001000000
2    radha              heart             101000000
3  krishna  inside that heart             124456789

In [51]:
df.drop(3,inplace=True)

In [52]:
df

            name       age     city
0          nidhi        20  lucknow
1         bhaiya        22  newyork
2  radha krishna  20000000    heart

In [53]:
df.describe()

                age
count  3.000000e+00
mean   6.666681e+06
std    1.154699e+07
min    2.000000e+01
25%    2.100000e+01
50%    2.200000e+01
75%    1.000001e+07
max    2.000000e+07